language: python
python:
  - "2.7"

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: pip install bottle
# command to run tests, e.g. python setup.py test
script: python server/test/test_readability-svr.py
notifications:
 email:
  recipients:
   - pcooley@gmail.com
   - jhelm@usa.net
