// 
// The basic interface for the readability
// 
//

struct lineScore {
  lineNo    int
  lineTxt   string
  lineScore int
}

struct ReadabilityRequest {
  reqData string
}

struct ReadabilityResponse {
  resultCode int
  docScore int
  lineScores []lineScore
}

interface ReadabilityService {
  
  readability(req ReadabilityRequest) ReadabilityResponse
  version() string

}
